# Generated by Django 3.1.7 on 2021-02-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='price',
            field=models.BigIntegerField(verbose_name='Price'),
        ),
    ]
