# Generated by Django 3.1.7 on 2021-02-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20210220_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
